name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: echo "$USER" 

    - name: alae
      run: echo -e 'int main(){\nprintf("hey")}' > file.c; apt install gcc; gcc file.c; ./a.out
